default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        exclude: 'settings'
  - repo: https://github.com/psf/black
    rev: '23.1.0'
    hooks:
      - id: black
        exclude: 'migrations*|urls*|settings*'
  - repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
        # NB The "exclude" setting in setup.cfg is ignored by pre-commit
        exclude: 'migrations*|urls*|settings*'
