services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
    # command: ["postgres", "-c", "log_connections=all", "-c", "log_disconnections=all", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "5432:5432"

  s3:
    image: minio/minio:edge-cicd
    environment:
      MINIO_DOMAIN: localhost # virtual hosted-style access
      MINIO_ROOT_USER: cleanpython
      MINIO_ROOT_PASSWORD: cleanpython
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 2s
      retries: 10
      timeout: 1s

  fluentbit:
    image: fluent/fluent-bit:1.9
    ports:
      - "24224:24224"

  rabbitmq:
    image: "rabbitmq:3-alpine"
    environment:
      RABBITMQ_DEFAULT_USER: "cleanpython"
      RABBITMQ_DEFAULT_PASS: "cleanpython"
      RABBITMQ_DEFAULT_VHOST: "cleanpython"
    ports:
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 1s
      retries: 5
