version: "3.8"

services:

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "cleanpython_test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    # command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    command:
      [
        "postgres",
        "-c",
        "log_connections=on",
        "-c",
        "log_disconnections=on",
        "-c",
        "log_destination=stderr"
      ]
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
