version: "3.8"

services:

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
    # command: ["postgres", "-c", "log_connections=all", "-c", "log_disconnections=all", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "5432:5432"

  s3:
    image: minio/minio:edge-cicd
    environment:
      MINIO_DOMAIN: localhost # virtual hosted-style access
      MINIO_ROOT_USER: cleanpython
      MINIO_ROOT_PASSWORD: cleanpython
    ports:
      - "9000:9000"
