name: Linux

# Run on PR requests. And on master itself.
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 8 * * 1' # Runs at 08:00 UTC every Monday

jobs:
  test:
    name: Test, Linux, Python ${{ matrix.python }}, ${{ matrix.versions }}
    runs-on: ubuntu-latest
    env:
      extras: "fastapi,auth,celery,fluentbit,sql,sql-sync,s3,s3-sync,api-client,amqp,nanoid,test"
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.10"
            pins: "psycopg2-binary==2.9.3"
            versions: "minimum"
          - python: "3.11"
            pins: "psycopg2-binary==2.9.3"
            versions: "minimum"
          - python: "3.12"
            pins: "psycopg2-binary"
            versions: "latest"
          - python: "3.13"
            pins: "psycopg2-binary"
            versions: "latest"

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

      s3:
        image: minio/minio:latest
        env:
          MINIO_DOMAIN: localhost  # virtual hosted-style access
          MINIO_ROOT_USER: cleanpython
          MINIO_ROOT_PASSWORD: cleanpython
        ports:
          - 9000:9000

      rabbitmq:
        image: "rabbitmq:3-alpine"
        env:
          RABBITMQ_DEFAULT_USER: "cleanpython"
          RABBITMQ_DEFAULT_PASS: "cleanpython"
          RABBITMQ_DEFAULT_VHOST: "cleanpython"
        ports:
          - "5672:5672"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: ${{ matrix.allow-prereleases || false }}

      - name: Install python dependencies
        run: |
          pip install --disable-pip-version-check --upgrade pip setuptools packaging pip-tools

      - name: Compile and install ${{ matrix.versions }} requirements
        run: "scripts/install_${{ matrix.versions }}.sh"
        shell: bash
        env:
          PINS: ${{ matrix.pins }}

      - name: Run tests
        run: pytest tests --cov

      - name: Wait for postgres
        run: scripts/wait-for-postgres.sh
        env:
          POSTGRES_URL: 'postgres:postgres@localhost:5432'
        timeout-minutes: 1

      - name: Run integration tests
        run: pytest integration_tests
        env:
          POSTGRES_URL: 'postgres:postgres@localhost:5432'
          S3_URL: 'http://localhost:9000'

  notify:
    name: Create issue in case of failed build
    needs: [test]
    if: failure() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: jayqi/failed-build-issue-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
